### ISSUE TITLE
Bundler 1.1.3 fails to load

### ISSUE THREAD

**Issue by ashchan** [wayneeseguin/rvm-capistrano#2]
After adding 'rvm-capistrano' to a Rails 3.2.2 project, it fails to start:

```
/Users/james/.rvm/gems/ruby-1.9.3-p125-perf/gems/bundler-1.1.3/lib/bundler/runtime.rb:77:in `rescue in rescue in block in require': undefined method `gsub' for nil:NilClass (NoMethodError)
    from /Users/james/.rvm/gems/ruby-1.9.3-p125-perf/gems/bundler-1.1.3/lib/bundler/runtime.rb:72:in `rescue in block in require'
    from /Users/james/.rvm/gems/ruby-1.9.3-p125-perf/gems/bundler-1.1.3/lib/bundler/runtime.rb:62:in `block in require'
    from /Users/james/.rvm/gems/ruby-1.9.3-p125-perf/gems/bundler-1.1.3/lib/bundler/runtime.rb:55:in `each'
    from /Users/james/.rvm/gems/ruby-1.9.3-p125-perf/gems/bundler-1.1.3/lib/bundler/runtime.rb:55:in `require'
    from /Users/james/.rvm/gems/ruby-1.9.3-p125-perf/gems/bundler-1.1.3/lib/bundler.rb:119:in `require'
    from /Users/james/Projects/idaily-app/config/application.rb:10:in `<top (required)>'
``

The application.rb:10 line was for assets pipeline:

```

Bundler.require(*Rails.groups(:assets => %w(development test)))

```
```

**Comment by gravis** [comment]
Revival this error. I'm getting this with the latest bundler now (1.8.0).
Bundler 1.7.x are working fine.
Thanks

**Comment by OscarBarrett** [comment]
Same here.

Adding `require: false` to rvm-capistrano in the Gemfile should prevent it from occurring for now.

**Comment by krt** [comment]
+1

**Comment by LydiaTripp** [comment]
+1

I am getting this error with bundler 1.8.2.  Adding require: false does work for now.

**Comment by mugurel-chirica** [comment]
I fix this error my moving rvm-capistrano gem before capistrano, like this:

# Deploy with Capistrano
gem 'rvm-capistrano'
gem 'capistrano'
